# Generated by Django 3.1.2 on 2021-01-13 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('postdate', models.DateField()),
                ('modifydate', models.DateField()),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('ratio', models.IntegerField()),
                ('postdate', models.DateField()),
                ('modifydate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('ratio', models.IntegerField()),
                ('postdate', models.DateField()),
                ('modifydate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Popularity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('postdate', models.DateField()),
                ('modifydate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Wallpapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('postdate', models.DateField()),
                ('modifydate', models.DateField()),
                ('size', models.IntegerField()),
                ('ratio', models.IntegerField()),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallpaper.category')),
            ],
        ),
        migrations.DeleteModel(
            name='wallpaperModel',
        ),
        migrations.AddField(
            model_name='popularity',
            name='wallpaperId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallpaper.wallpapers'),
        ),
        migrations.AddField(
            model_name='likes',
            name='likesId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallpaper.user'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='favouriteId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallpaper.user'),
        ),
    ]
