# Generated by Django 3.1.2 on 2021-01-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0003_auto_20210129_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='wallpapers',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='Images/'),
        ),
    ]
